image:
  repository: eu.gcr.io/gardener-project/gardener/extensions/shoot-dns-service
  tag: latest
  pullPolicy: IfNotPresent

serviceName: shoot-dns-service
dnsClass: garden
# dnsActivation: <shoot dns subdomain>

dnsProviderReplication:
  enabled: false

gardener:
  seed:
    identity: ""


resources:
  requests:
   cpu: "50m"
   memory: "64Mi"
  limits:
   cpu: "50m"
   memory: "128Mi"

vpa:
  enabled: true
  resourcePolicy:
    minAllowed:
      cpu: 25m
      memory: 50Mi
  updatePolicy:
    updateMode: "Auto"

controllers:
  lifecycle:
    concurrentSyncs: 5
  healthcheck:
    concurrentSyncs: 5
  replication:
    concurrentSyncs: 5
  ignoreOperationAnnotation: false

# imageVectorOverwrite: |
#   images:
#   - name: dns-controller-manager
#     sourceRepository: github.com/gardener/external-dns-management
#     repository: eu.gcr.io/gardener-project/dns-controller-manager
#     tag: "0.7.1"
