images:
- name: dns-controller-manager
  sourceRepository: github.com/gardener/external-dns-management
  repository: eu.gcr.io/gardener-project/dns-controller-manager
  tag: "v0.10.5-dev-8989ee2ff396580412706825b5054bad7cb58e49"
